django_work/django_work/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('telekoko/', include('telekoko.urls')),
]

django_work/telekoko/urls.py
from django.urls import path
from . import views

app_name = "telekoko"            
urlpatterns = [
    path("", views.index, name='index'),
    path("telekoko/create/",views.feeling_create, name = "feeling_create")
]

django_work/telekoko/models.py
from django.db import models
import uuid

class Group(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
  group_name = models.CharField(max_length=50, verbose_name="グループ名")
  created_at = models.DateTimeField(auto_now_add=True, verbose_name="登録日時")
  updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")
  is_deleted = models.BooleanField(default=False, verbose_name="削除フラグ")
  
  def __str__(self):
        return self.group_name

class GroupUser(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
  group = models.ForeignKey('Group', on_delete=models.CASCADE, verbose_name="グループID")
  user = models.ForeignKey('User', on_delete=models.CASCADE, verbose_name="ユーザID")

  def __str__(self):
        return f"{self.group.name} ・ {self.user.name}"

class User(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
  name = models.CharField(max_length=50, verbose_name="名前")
  feeling = models.ForeignKey('Feeling',on_delete=models.PROTECT, verbose_name="気持ちID")
  created_at = models.DateTimeField(auto_now_add=True, verbose_name="登録日時")
  updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")
  is_deleted = models.BooleanField(default=False, verbose_name="削除フラグ")

  def __str__(self):
      return self.name



class Feeling(models.Model):
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
  name = models.CharField(max_length=50, verbose_name="気持ち名")
  feeling_image = models.ImageField(upload_to="image", blank=True, verbose_name="気持ちイメージ", help_text="登録しない場合は、デフォルトの気持ちイメージを使用する")
  created_at = models.DateTimeField(auto_now_add=True, verbose_name="登録日時")
  updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")
  is_deleted = models.BooleanField(default=False, verbose_name="削除フラグ")
  
  def __str__(self):
      return self.name

django_work/telekoko/forms.py
from django.forms import ModelForm
from .models import User


class UserForm(ModelForm):
  class Meta:
    model = User
    fields = ["feeling"]

django_work/telekoko/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserForm

class IndexView(View):
    def get(self,request):
          return render(request, "telekoko/index.html")


class FeelingCreateView(View):
    #初期表示
    def get(self, request):
        form = UserForm()
        return render(request,"telekoko/feeling_form.html",{"form": form})
    #保存処理（保存後はトップページにリダイレクト、失敗すれば遷移しない）
    def post(self,request):
        form  = UserForm(request.post)
        if form.is_valid():
            form.save()
            return redirect("telekoko:index")
        return render(request, "telekoko/feeling_form.html",{"form": form})

index = IndexView.as_view()
feeling_create = FeelingCreateView.as_view()

django_work/templates/telekoko/feeling_form.html
<!DOCTYPE html>
<html lang="ja">
  <head>
      <meta charset="utf-8" />
      <title>今日は、こんな気持ち。</title>
  </head>
  <body>
    <h2>気持ちを登録する</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">保存</button>
    </form>
  </body>
</html>

django_work/templates/telekoko/index.html
<!DOCTYPE html>
<html lang="ja">
  <head>
      <meta charset="utf-8" />
      <title>今日は、こんな気持ち。</title>
  </head>
  <body>
    <header>
      <h1>今日は、こんな気持ち。</h1>
      <nav>
        <div><a href="#">新規登録</a></div>
          <div><a href="#">ログイン</a></div>
      </nav>
    </header>
    <section>
      <div>
      <p>みんなと今の気持ちをシェアしてみよう！</p>
      <p>できること</p>
      <ul>
        <li>
          <p>自分の気持ちを絵文字で見える化できる</p>
        </li>
        <li>
          <p>自分の気持ちを相手とシェアできる</p>
        </li>
      </ul>
      </div>
      <div>
        <a href="{% url 'telekoko:feeling_create' %}">気持ちを登録する</a>
      </div>
    </section>
  </body>
</html>